name: Caller workflow
on:
  push:
    branches:
      - main

jobs:
  CallOtherWorkflow:
    # uses: ./.github/workflows/callee.yml@main
    uses: ./.github/workflows/callee.yml@main
    with:
      foo: bar
      # baz: bat
