name: Caller workflow
on:
  push:
    branches:
      - main

jobs:
  CallOtherWorkflow:
    uses: ./.github/workflows/callee.yml
    with:
      foo: bar

  PrintFormattedValue:
    runs-on: ubuntu-latest
    needs: [CallOtherWorkflow]
    steps:
      - name: Print formatted
        id: printFormatted
        run: |
          echo "Value formatted by called workflow: ${{ needs.CallOtherWorkflow.outputs.formattedJSON }}"
