name: Callee workflow
on:
  workflow_call:
    inputs:
      foo:
        required: true
        type: string
        description: foo value
      baz:
        required: false
        type: string
        description: baz value
        default: bat

    outputs:
      formattedJSON:
        description: The formatted JSON value
        value: ${{ jobs.FormatJSON.outputs.formattedJSON }}

jobs:
  FormatJSON:
    runs-on: ubuntu-latest
    outputs:
      formattedJSON: ${{steps.setFormattedJSON.outputs.out}}
    steps:
      - name: Set formatted JSON for output
        id: setFormattedJSON
        run: |
          echo "out={ \"foo\": \"${{ inputs.foo }}\", \"baz\": \"${{ inputs.baz }}\" }" >> $GITHUB_OUTPUT
